services:
  # PostgreSQL database
  postgresql_db:
    image: postgres:17.7-alpine
    container_name: postgresql-db
    restart: always
    ports:
      - "5432:5432" # Default PostgreSQL port
    environment:
      POSTGRES_PASSWORD: postgresql
    volumes:
      - postgresql_db_data:/var/lib/postgresql/data # Docker managed volume
  # Redis Database
  redis:
    image: redis:8.4-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgresql_db_data:
  redis_data:
    driver: local
